# Site
name: "Sandy Su"
title: "Health Tech Bytes"
description: "Where health and technology meet, one byte at a time."
email: sandylsu@gmail.com
medium: https://medium.com/@sandylsu
twitter: https://twitter.com/sandylsu
linkedin: https://www.linkedin.com/in/sandylsu/
github: https://github.com/slsu0424
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl:
#google_analytics: 'UA-46278016-1'
google_analytics: 'G-Q7BBEPH7PT'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
blog: "Health Tech Bytes"

# Authors
authors:
  sandy:
    name: Sandy
    display_name: Sandy
    gravatar: 2805ebc521560def5e29b70a496914f63b35e8c268b2022558b1e3619270d41f
    email: sandylsu@gmail.com
    web: https://www.linkedin.com/in/sandylsu/
    # web: https://medium.com/@sandylsu
    twitter: https://twitter.com/sandylsu
    description: "Author at Health Tech Bytes. Healthcare technology advisor, cloud architect, data science and AI practitioner"
  john:
    name: John
    display_name: John    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
#paginate_path: /page:num/
paginate_path: /blog/page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
